# Generated by Django 4.2.7 on 2023-11-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingATREvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                "db_table": "pending_atr_event",
            },
        ),
        migrations.CreateModel(
            name="PendingATREventMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                "db_table": "pending_atr_event_master",
            },
        ),
        migrations.CreateModel(
            name="PendingATRLocos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                "db_table": "pendint_atr_locos",
            },
        ),
    ]
